### ISSUE TITLE
Should I use the package on production?

### ISSUE THREAD

**Issue by anwardote** [spatie/laravel-cronless-schedule#4]
Hi,

Thank you for another awesome package. It looks like a very interesting package. 

However, it works nicely in the test environment. Don't you prefer using this in a production environment? why? or Why not?

Thank you in advance.

Anwar

**Comment by freekmurze** [comment]
I'm thinking it should work fine in production. 

Personally I stick to cron for production, because cron has a proven track record. It's being used by millions and is rock solid.

**Comment by anwardote** [comment]
Thank you for your quick reply.
