### ISSUE TITLE
Not working on windows

### ISSUE THREAD

**Issue by ScriptingBeating** [spatie/laravel-cronless-schedule#5]
Getting this error. When I run php artisan schedule:run-cronless

 Unable to set stream resource to non-blocking mode

  at C:\Users\mohan\Desktop\ExamPanel\vendor\react\stream\src\ReadableResourceStream.php:56
    
            // this class relies on non-blocking I/O in order to not interrupt the event loop
            // e.g. pipes on Windows do not support this: https://bugs.php.net/bug.php?id=47918
           if (\stream_set_blocking($stream, false) !== true) {
               throw new \RuntimeException('Unable to set stream resource to non-blocking mode');
           }

**Comment by freekmurze** [comment]
I'm not a Windows user, so I'm not going to invest time in this.

I'm accepting a PR that fixes this.

**Comment by vnzko** [comment]
What kind of fix do you expect ? This issue is realated to to [clue/reactphp-stdio](https://github.com/clue/reactphp-stdio) and it's pretty clear in the readme that the lib doesn't support Windows because async console i/o isn't supported.

The only solution I see is to throw an exception to make it clear.

**Comment by vdkar** [comment]
I have the same problem ( I'm also waiting for a solution

**Comment by freekmurze** [comment]
The dependencies this package uses do not support Windows and I doubt if they ever will.

**Comment by ScriptingBeating** [comment]
> The dependencies this package uses do not support Windows and I doubt if they ever will.

@freekmurze  Certainly not as Microsoft dropped the support for PHP.

**Comment by vnzko** [comment]
@ScriptingBeating Microsoft is dropping the support for something they aren't related too ?

**Comment by ScriptingBeating** [comment]
@vnzko check out this article. https://laravel-news.com/microsoft-dropping-php-support

**Comment by vnzko** [comment]
Oh i didn't know that. Weird move from MS. 

The problem related to this package isn't really php related but how windows is handling I/O on console program.

**Comment by ScriptingBeating** [comment]
> The problem related to this package isn't really php related but how windows is handling I/O on console program.

Yeah and might not be fixable I think.
